Repository mongodb/devhub, pull requests merged in 2020-09, with the labels that each got.

#486 (Merge Sept. 2) Revert "DEVHUB-205: Add support for statcounter"
  cypress/integration/article.js
  cypress/support/commands.js
  gatsby-ssr.js
Labels: do not merge

#498 Disable Dropdown Selects when Text Filtering
  src/components/dev-hub/filter-bar.js
  src/components/dev-hub/select.js
Labels: enhancement

#495 Add Text Filter to Learn Page
  package.json
  src/components/dev-hub/filter-bar.js
  src/components/dev-hub/select.js
  src/components/dev-hub/text-filter-input.js
  src/hooks/use-text-filter.js
  src/pages/learn.js
Labels: user-facing feature release

#497 DOP-1409: Support new AST structure for target IDs
  src/components/DefinitionListItem.js
  src/components/RefRole.js
  src/components/Target.js
  src/utils/find-key-value-pair.js
Labels: do not merge

#522 Fix CardList Flash on "Load More"
  src/components/dev-hub/card-list.js
Labels: bug
