Repository mongodb/devhub, pull requests merged in 2021-04, with the labels that each got.

#757 DEVHUB-556: Create Podcast Pages
  gatsby-node.esm.js
  src/templates/podcast.js
  src/utils/get-tag-page-uri-component.js
  src/utils/setup/create-podcast-pages.js
  src/utils/setup/fetch-build-time-media.js
  src/utils/setup/handle-create-page.js
Labels: enhancement

#758 DEVHUB-593: Prepare to use CMS Feedback Questions
  gatsby-config.js
  gatsby-config.prod.js
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/index.js
  src/queries/fragments/feedback.js
  src/templates/article.js
Labels: build-time logic

#761 DEBHUB-602: Star Rating
  src/components/ArticleRating.js
  src/components/dev-hub/icons/star-icon.js
  src/components/dev-hub/star-rating.js
  src/templates/article.js
  tests/unit/StarRating.test.js
  tests/unit/__snapshots__/StarRating.test.js.snap
Labels: do not merge, enhancement, front-end

#760 DEVHUB-592: Create a Generalized Form
  src/components/dev-hub/cms-form.js
  src/components/dev-hub/feedback/feedback-container.js
  src/queries/fragments/feedback.js
  src/templates/article.js
Labels: enhancement, front-end

#764 Fix series CSS post emotion 11
  src/components/dev-hub/series.js
Labels: bug, front-end

#765 Deploy: Fix series CSS post emotion 11 (#764)
  src/components/dev-hub/series.js
Labels: Release

#767 Skunkworks: Add Simple TTR at Build Time
  src/queries/articles.js
  src/utils/setup/create-article-node.js
  src/utils/setup/get-time-to-read.js
  tests/utils/create-article-node.test.js
Labels: build-time logic

#768 WIP: Add TTR to Article Headers
  gatsby-node.esm.js
  src/components/dev-hub/blog-post-title-area.js
  src/components/dev-hub/icons/clock.js
  src/templates/article.js
  src/utils/setup/create-article-page.js
  tests/utils/create-article-page.test.js
Labels: build-time logic, front-end

#770 DEVHUB-594 (prep): Add Endpoints for Form Submission
  src/constants.js
  src/utils/devhub-api-stitch.js
Labels: enhancement

#766 DEVHUB-501, DEVHUB-613: April 2021 Dep Updates
  .storybook/webpack.config.js
  package-lock.json
  package.json
Labels: technical debt

#769 DEV-HUB-611: Implement modal window and style it
  src/components/ArticleRating.js
  src/components/dev-hub/cms-form.js
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/helpers/getStarRatingFlow.js
  src/components/dev-hub/feedback/index.js
  src/templates/article.js
Labels: enhancement, front-end

#774 Deploy April 2021 Dep Updates
  .storybook/webpack.config.js
  package-lock.json
  package.json
Labels: Release

#775 DEVHUB-610: Implement star rating for article page
  src/components/ArticleRating.js
  src/components/dev-hub/article-share-footer.js
  src/templates/article.js
  tests/unit/ArticleRating.test.js
  tests/unit/__snapshots__/ArticleRating.test.js.snap
Labels: enhancement, front-end

#777 DEVHUB-595
  src/components/ArticleRating.js
  src/components/ArticleRatingContext.js
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/cms-form.js
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/feedback-context.js
  src/components/dev-hub/feedback/feedback-final-step.js
  src/components/dev-hub/feedback/feedback-form.js
  src/components/dev-hub/feedback/helpers/getStarRatingFlow.js
  src/components/dev-hub/modal.js
  src/components/dev-hub/star-rating.js
  src/hooks/use-feedback.js
  src/templates/article.js
  tests/unit/ArticleRating.test.js
  tests/unit/StarRating.test.js
  tests/unit/__snapshots__/ArticleRating.test.js.snap
  tests/unit/__snapshots__/StarRating.test.js.snap
  tests/unit/mock/MockArticleRatingProvider.js
Labels: enhancement, front-end

#781 DEVHUB-585: Add Strapi Articles to Search Indexing, RSS Feed
  src/queries/rss-feed-article-data.js
  src/queries/search-article-rss-data.js
  src/utils/setup/serialize-rss-data.js
  src/utils/setup/serialize-search-rss-data.js
  src/utils/transform-article-strapi-data.js
Labels: enhancement

#785 Add podcast descriptions
  package-lock.json
  package.json
  src/utils/parse-podcasts.js
Labels: enhancement

#787 DEVHUB-626: Part 2 of Design UAT
  src/components/dev-hub/feedback/feedback-final-step.js
Labels: enhancement
