Repository mongodb/devhub, pull requests merged in 2021-05, with the labels that each got.

#790 DEVHUB-619: Use shouldForwardProps for invalid props
  src/components/dev-hub/card.js
  src/components/pages/academia/students-educators-details.js
Labels: enhancement

#791 Deploy May 3rd 2021
  package-lock.json
  package.json
  src/components/dev-hub/card.js
  src/components/pages/academia/students-educators-details.js
  src/utils/parse-podcasts.js
Labels: Release

#793 Support the case for zero Strapi articles, fix withPrefix use
  gatsby-node.esm.js
  src/classes/snooty-article.ts
  src/queries/rss-feed-article-data.js
  src/queries/search-article-rss-data.js
  src/utils/setup/create-article-node.js
  src/utils/setup/get-strapi-article-list-from-graphql.js
  src/utils/setup/schema-customization.js
  src/utils/setup/serialize-rss-data.js
  src/utils/setup/serialize-search-rss-data.js
Labels: build-time logic

#794 Set defaults for Strapi to avoid failing builds
  src/utils/transform-article-strapi-data.js
Labels: enhancement

#795 Misc Strapi Parity Fixes
  src/classes/snooty-article.ts
  src/classes/strapi-article.ts
  src/components/dev-hub/blog-post-title-area.js
  src/components/dev-hub/card-list.js
  src/components/pages/home/hero.js
  src/utils/setup/find-articles-from-slugs.js
Labels: enhancement

#783 DEVHUB-555: Create New Podcast Player
  src/components/dev-hub/icons/audio-player/fast-forward-icon.js
  src/components/dev-hub/icons/audio-player/index.js
  src/components/dev-hub/icons/audio-player/logos/apple-logo.js
  src/components/dev-hub/icons/audio-player/logos/google-logo.js
  src/components/dev-hub/icons/audio-player/logos/spotify-logo.js
  src/components/dev-hub/icons/audio-player/pause-icon.js
  src/components/dev-hub/icons/audio-player/play-icon.js
  src/components/dev-hub/icons/audio-player/rewind-icon.js
  src/components/dev-hub/podcast-player/audio-player.js
  src/components/dev-hub/podcast-player/player-contols.js
  src/components/dev-hub/podcast-player/player-listen-on.js
  src/components/dev-hub/podcast-player/player-reducer.js
  src/components/dev-hub/slider.js
  src/templates/podcast.js
  tests/unit/PlayerControls.test.js
  tests/unit/PlayerListenOn.test.js
  tests/unit/__snapshots__/PlayerControls.test.js.snap
  tests/unit/__snapshots__/PlayerListenOn.test.js.snap
Labels: enhancement, front-end

#797 Fix Missing Author Bios, Handle Empty Data
  gatsby-config.js
  gatsby-config.prod.js
  gatsby-node.esm.js
  src/templates/article.js
  src/utils/map-tag-type-to-url.js
  src/utils/setup/create-article-node.js
  src/utils/setup/create-strapi-author-pages.js
  src/utils/setup/schema-customization.js
  src/utils/setup/serialize-search-rss-data.js
Labels: build-time logic, enhancement

#799 Cleanup Proptypes and Enable Related Links
  src/classes/strapi-article.ts
  src/components/Emphasis.js
  src/components/List.js
  src/components/Literal.js
  src/components/Reference.js
  src/queries/articles.js
  src/utils/setup/schema-customization.js
  src/utils/transform-article-strapi-data.js
Labels: enhancement

#800 Deploy: Additional Strapi Directive Support
  package-lock.json
  package.json
  src/classes/strapi-article.ts
  src/components/ComponentFactory.js
  src/components/Emphasis.js
  src/components/Image.js
  src/components/List.js
  src/components/Literal.js
  src/components/Reference.js
  src/components/dev-hub/raw-html.js
  src/components/dev-hub/searchbar/SearchResult.js
  src/queries/articles.js
  src/utils/setup/parse-markdown-to-ast.js
  src/utils/setup/schema-customization.js
  src/utils/transform-article-strapi-data.js
Labels: Release

#804 DEVHUB-638: Expose Links on Articles
  src/components/ArticleRatingContext.js
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-share-links.js
  src/components/dev-hub/contents-menu.js
  src/components/dev-hub/controlled-tooltip.js
  src/components/dev-hub/hover-tooltip.js
  src/components/dev-hub/icons/link-icon.js
  src/components/dev-hub/icons/linkedin.js
  src/components/dev-hub/icons/star-icon.js
  src/templates/article.js
Labels: enhancement, front-end

#788 DEVHUB-601: Implement Design on Podcast Page
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-post-title-area.js
  src/components/dev-hub/podcast-jumbotron.js
  src/components/dev-hub/podcast-player/audio-player.js
  src/constants.js
  src/templates/article.js
  src/templates/podcast.js
  src/utils/setup/create-podcast-pages.js
  tests/unit/PodcastJumbotron.test.js
  tests/unit/__snapshots__/PodcastJumbotron.test.js.snap
  tests/unit/data/PodcastJumbotron.test.json
Labels: enhancement, front-end

#806 DEPLOY DEVHUB-649: Add support for the charts directive (#805)
  src/utils/setup/parse-markdown-to-ast.js
Labels: Release

#812 DEVHUB-660: Default to H2 and above for TOC
  src/utils/find-section-headings.js
Labels: build-time logic

#813 DEVHUB-653: Properly render anchor tags from Strapi
  src/components/Link.js
Labels: bug, front-end

#814 Null Check Author Images from Strapi
  src/utils/setup/transform-author-strapi-data.js
Labels: bug

#815 Remove unused debug param since signature changed
  src/classes/strapi-article.ts
Labels: bug

#817 Use Component Factory to compose styles
  src/components/Emphasis.js
  src/components/Reference.js
  src/components/Strong.js
  tests/unit/__snapshots__/Emphasis.test.js.snap
  tests/unit/__snapshots__/Strong.test.js.snap
Labels: enhancement

#818 Correctly get Strapi preview URLs for social share
  src/utils/transform-article-strapi-data.js
Labels: bug

#819 Deploy Misc Strapi Cleanup
  src/classes/strapi-article.ts
  src/components/Emphasis.js
  src/components/Link.js
  src/components/Reference.js
  src/components/Strong.js
  src/utils/find-section-headings.js
  src/utils/setup/transform-author-strapi-data.js
  src/utils/transform-article-strapi-data.js
  tests/unit/__snapshots__/Emphasis.test.js.snap
  tests/unit/__snapshots__/Strong.test.js.snap
Labels: Release

#811 DEVHUB-557: Swap Podcast functionality on Learn Page
  gatsby-node.esm.js
  src/components/dev-hub/card-list.js
  src/pages/learn.js
  src/utils/setup/create-podcast-pages.js
  src/utils/setup/handle-create-learn-page.js
  src/utils/setup/handle-create-page.js
Labels: enhancement

#820 DEVHUB-651: Add Table, TableRow, and TableCell support for Strapi
  src/components/ComponentFactory.js
  src/components/Table.js
  src/components/TableCell.js
  src/components/TableRow.js
Labels: enhancement

#821 DEVHUB-670: Don't sort by date for search results
  src/components/dev-hub/card-list.js
  src/pages/learn.js
Labels: bug

#816 DEVHUB-661: Adds interfaces and classes for video content
  src/classes/twitch-video.ts
  src/classes/youtube-video.ts
  src/components/ListTable.js
  src/interfaces/responses/twitch-response.ts
  src/interfaces/responses/youtube-response.ts
  src/interfaces/video.ts
  src/types/video-type.ts
  src/utils/fetch-twitch-videos.js
  src/utils/fetch-youtube-data.js
  src/utils/setup/fetch-build-time-media.js
  src/utils/simplify-twitch-response.js
  src/utils/simplify-youtube-response.js
  src/utils/transform-twitch-response.ts
  src/utils/transform-youtube-response.ts
Labels: enhancement

#822 Deploy (Monday, May 17): Search Sort Bug
  src/components/ComponentFactory.js
  src/components/Table.js
  src/components/TableCell.js
  src/components/TableRow.js
  src/components/dev-hub/card-list.js
  src/pages/learn.js
Labels: Release

#825 DEVHUB-666: Fix feedback missing title, authors, inconsistent slashes
  src/components/dev-hub/feedback/feedback-container.js
  src/templates/article.js
Labels: bug

#826 DEVHUB-665: Don't clear stars if is last modal
  src/components/ArticleRatingContext.js
  src/components/dev-hub/feedback/feedback-container.js
Labels: enhancement

#827 DEVHUB-625: Remove Modal Border, Add Last Modal Padding
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/feedback-final-step.js
Labels: enhancement

#830 DEVHUB-625: Use old check UX for copy, change hover color
  cypress/integration/article.js
  src/components/dev-hub/blog-share-links.js
Labels: enhancement

#829 DEVHUB-625: Use consistent spacing for text elements on modals
  src/components/dev-hub/feedback/feedback-form.js
Labels: enhancement

#824 DEVHUB-662: Video Template
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-post-title-area.js
  src/components/dev-hub/hero-banner.js
  src/constants.js
  src/templates/video.js
Labels: enhancement, front-end

#823 Podcasts: Add Exposed Links for Social Sharing
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-share-links.js
  src/components/dev-hub/contents-menu.js
  src/components/dev-hub/controlled-tooltip.js
  src/components/dev-hub/hover-tooltip.js
  src/components/dev-hub/icons/link-icon.js
  src/components/dev-hub/icons/linkedin.js
  src/templates/article.js
  src/templates/podcast.js
Labels: enhancement

#828 DEVHUB-663: Replace Video Functionality on the Learn Page
  gatsby-node.esm.js
  src/classes/twitch-video.ts
  src/classes/youtube-video.ts
  src/components/dev-hub/card-list.js
  src/interfaces/video.ts
  src/pages/learn.js
  src/templates/video.tsx
  src/utils/get-tag-page-uri-component.js
  src/utils/setup/create-video-pages.ts
  src/utils/setup/fetch-build-time-media.js
  src/utils/setup/handle-create-page.js
Labels: enhancement, front-end

#832 DEVHUB-664: Add useViewport hook for mobile
  src/components/dev-hub/feedback/feedback-container.js
  src/hooks/use-viewport.js
Labels: bug

#833 DEVHUB-666: Add Leading Slashes to Feedback Slugs
  src/templates/article.js
  src/utils/add-leading-slash-if-missing.js
  tests/utils/add-leading-slash-if-missing.test.js
Labels: enhancement

#836 DEVHUB-679 DEVHUB-682: Accessibility, Unique IDs
  src/components/ArticleRating.js
  src/components/dev-hub/blog-share-links.js
  src/components/dev-hub/icons/star-icon.js
  src/components/dev-hub/icons/success.js
  src/components/dev-hub/share-menu.js
  src/components/dev-hub/star-rating.js
  src/templates/article.js
Labels: enhancement

#837 DEVHUB-664: Use height: fit-content for zoomed in content
  src/components/dev-hub/feedback/feedback-container.js
Labels: bug

#838 Merge DevHub Feedback to Staging
  cypress/integration/article.js
  gatsby-config.js
  gatsby-config.prod.js
  src/components/ArticleRating.js
  src/components/ArticleRatingContext.js
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-share-links.js
  src/components/dev-hub/cms-form.js
  src/components/dev-hub/contents-menu.js
  src/components/dev-hub/controlled-tooltip.js
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/feedback-context.js
  src/components/dev-hub/feedback/feedback-final-step.js
  src/components/dev-hub/feedback/feedback-form.js
  src/components/dev-hub/feedback/helpers/getStarRatingFlow.js
  src/components/dev-hub/feedback/index.js
  src/components/dev-hub/feedback/star-rating-list.js
  src/components/dev-hub/hover-tooltip.js
  src/components/dev-hub/icons/balloons-icon.js
  src/components/dev-hub/icons/link-icon.js
  src/components/dev-hub/icons/linkedin.js
  src/components/dev-hub/icons/star-icon.js
  src/components/dev-hub/icons/success.js
  src/components/dev-hub/modal.js
  src/components/dev-hub/share-menu.js
  src/components/dev-hub/star-rating.js
  src/constants.js
  src/hooks/use-feedback.js
  src/hooks/use-viewport.js
  src/queries/fragments/feedback.js
  src/templates/article.js
  src/utils/add-leading-slash-if-missing.js
  src/utils/devhub-api-stitch.js
  tests/unit/ArticleRating.test.js
  tests/unit/StarRating.test.js
  tests/unit/__snapshots__/ArticleRating.test.js.snap
  tests/unit/__snapshots__/StarRating.test.js.snap
  tests/unit/mock/MockArticleRatingProvider.js
  tests/utils/add-leading-slash-if-missing.test.js
Labels: user-facing feature release

#840 Release DevHub Feedback
  cypress/integration/article.js
  gatsby-config.js
  gatsby-config.prod.js
  src/components/ArticleRating.js
  src/components/ArticleRatingContext.js
  src/components/dev-hub/article-share-footer.js
  src/components/dev-hub/blog-share-links.js
  src/components/dev-hub/cms-form.js
  src/components/dev-hub/contents-menu.js
  src/components/dev-hub/controlled-tooltip.js
  src/components/dev-hub/feedback/feedback-container.js
  src/components/dev-hub/feedback/feedback-context.js
  src/components/dev-hub/feedback/feedback-final-step.js
  src/components/dev-hub/feedback/feedback-form.js
  src/components/dev-hub/feedback/helpers/getStarRatingFlow.js
  src/components/dev-hub/feedback/index.js
  src/components/dev-hub/feedback/star-rating-list.js
  src/components/dev-hub/hover-tooltip.js
  src/components/dev-hub/icons/balloons-icon.js
  src/components/dev-hub/icons/link-icon.js
  src/components/dev-hub/icons/linkedin.js
  src/components/dev-hub/icons/star-icon.js
  src/components/dev-hub/icons/success.js
  src/components/dev-hub/modal.js
  src/components/dev-hub/share-menu.js
  src/components/dev-hub/star-rating.js
  src/constants.js
  src/hooks/use-feedback.js
  src/hooks/use-viewport.js
  src/queries/fragments/feedback.js
  src/templates/article.js
  src/utils/add-leading-slash-if-missing.js
  src/utils/devhub-api-stitch.js
  tests/unit/ArticleRating.test.js
  tests/unit/StarRating.test.js
  tests/unit/__snapshots__/ArticleRating.test.js.snap
  tests/unit/__snapshots__/StarRating.test.js.snap
  tests/unit/mock/MockArticleRatingProvider.js
  tests/utils/add-leading-slash-if-missing.test.js
Labels: Release, user-facing feature release

#839 DEVHUB-639: accessibility testing
  cypress/integration/home.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#835 DEVHUB-671: Video pages integration test
  cypress/integration/video.js
Labels: enhancement

#843 DEVHUB-218: Support Banners from Strapi
  cypress/integration/top-banner.js
  gatsby-config.js
  gatsby-config.prod.js
  src/components/dev-hub/layout.js
  src/components/dev-hub/top-banner.tsx
  src/utils/setup/schema-customization.js
Labels: enhancement

#845 Deploy, May 26th 2021
  cypress/integration/home.js
  cypress/integration/top-banner.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  gatsby-config.js
  gatsby-config.prod.js
  package-lock.json
  package.json
  src/components/dev-hub/layout.js
  src/components/dev-hub/top-banner.tsx
  src/utils/setup/schema-customization.js
  tsconfig.json
Labels: Release

#844 DEVHUB-596: Tab search
  src/components/dev-hub/layout.js
  static/opensearch.xml
Labels: enhancement, front-end

#841 DEVHUB-457: Breadcrumbs improvements.
  src/components/dev-hub/breadcrumb-schema.js
  src/components/dev-hub/hero-banner.js
  src/components/dev-hub/project-title-area.js
  src/components/pages/educators/top-banner.js
  src/templates/article.js
  src/templates/project.js
  tests/unit/BreadcrumbSchema.test.js
  tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
  tests/unit/data/BreadcrumbSchema.test.json
Labels: enhancement, front-end

#847 Deploy May 28th 2021
  src/components/dev-hub/breadcrumb-schema.js
  src/components/dev-hub/hero-banner.js
  src/components/dev-hub/layout.js
  src/components/dev-hub/project-title-area.js
  src/components/pages/educators/top-banner.js
  src/templates/article.js
  src/templates/project.js
  static/opensearch.xml
  tests/unit/BreadcrumbSchema.test.js
  tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
  tests/unit/data/BreadcrumbSchema.test.json
Labels: Release
