Repository mongodb/devhub, pull requests merged in 2021-03, with the labels that each got.

#700 DEVHUB-457: Structured data breadcrumbs: Implement breadcrumb schema to all pages
  src/components/dev-hub/breadcrumb-schema.js
  src/components/dev-hub/breadcrumb.js
  tests/unit/BreadcrumbSchema.test.js
  tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
  tests/unit/data/BreadcrumbSchema.test.json
Labels: enhancement

#706 [DEVHUB-117] Metadata needed for devhub blog posts
  cypress/integration/article.js
  src/components/dev-hub/article-schema.js
  src/templates/article.js
  tests/unit/ArticleSchema.test.js
  tests/unit/__snapshots__/ArticleSchema.test.js.snap
  tests/unit/data/ArticleSchema.test.json
Labels: enhancement

#716 DEVHUB-503: Move all instances of developer.mongodb.com to one variable in repo
  src/components/dev-hub/global-footer.js
  src/constants.js
  src/pages/code-for-good.js
  src/pages/community/index.js
  src/pages/index.js
  src/utils/make-link-internal-if-applicable.js
  tests/utils/make-link-internal-if-applicable.test.js
Labels: enhancement

#727 DEVHUB-552: Fix mailto link logic
  src/components/Link.js
  tests/unit/Link.test.js
  tests/unit/__snapshots__/Link.test.js.snap
Labels: enhancement

#735 DEVHUB-560: Implement page number into page title for numbered article pages
  cypress/integration/author.js
  cypress/integration/learn.js
  src/pages/learn.js
  src/templates/tag.js
Labels: enhancement, front-end

#734 DEVHUB-549: Search on devhub with / shortcut
  cypress/integration/search.js
  src/components/dev-hub/searchbar/ExpandedSearchbar.js
  src/components/dev-hub/searchbar/Searchbar.js
Labels: enhancement

#742 DEVHUB-549: Ensure slash key works on Firefox
  cypress/integration/search.js
  src/components/dev-hub/searchbar/Searchbar.js
Labels: front-end

#744 Deploy March 24th 2021
  cypress/integration/author.js
  cypress/integration/learn.js
  cypress/integration/search.js
  gatsby-config.js
  gatsby-config.prod.js
  gatsby-node.esm.js
  src/components/dev-hub/searchbar/ExpandedSearchbar.js
  src/components/dev-hub/searchbar/Searchbar.js
  src/pages/learn.js
  src/queries/client-side-redirects.js
  src/templates/tag.js
  src/utils/setup/create-client-side-redirects.js
Labels: Release

#747 Deploy: DEVHUB-553: Add Article raw_content to search XML (#745)
  cypress/integration/search.js
  gatsby-node.esm.js
  src/queries/search-article-rss-data.js
  src/utils/setup/create-article-node.js
  src/utils/setup/serialize-search-rss-data.js
  tests/utils/create-article-node.test.js
Labels: Release

#746 DEVHUB-508: Upgrade General Support to Node 14
  .github/workflows/devhub-ci-test.yaml
  .github/workflows/devhub-npm-test.yaml
Labels: enhancement

#736 DEVHUB-561: Implement a H1 to all paginated article pages which contains the page number
  cypress/integration/author.js
  cypress/integration/learn.js
  cypress/integration/tag.js
  src/pages/learn.js
  src/templates/tag.js
Labels: enhancement, front-end

#749 DEVHUB-566: Fix Pop-up on Search Results - MongoDB
  src/pages/learn.js
Labels: enhancement, front-end

#752 Deploy March 29th, 2021
  .github/workflows/devhub-ci-test.yaml
  .github/workflows/devhub-npm-test.yaml
  cypress/integration/author.js
  cypress/integration/learn.js
  cypress/integration/tag.js
  src/pages/learn.js
  src/templates/tag.js
Labels: Release

#755 DEVHUB-107: Update literal style
  src/components/Literal.js
  tests/unit/DefinitionList.test.js
  tests/unit/Literal.test.js
  tests/unit/__snapshots__/DefinitionList.test.js.snap
  tests/unit/__snapshots__/Literal.test.js.snap
Labels: front-end

#756 Deploy March 31, 2021
  src/components/Literal.js
  tests/unit/DefinitionList.test.js
  tests/unit/Literal.test.js
  tests/unit/__snapshots__/DefinitionList.test.js.snap
  tests/unit/__snapshots__/Literal.test.js.snap
Labels: Release
