Repository mongodb/devhub, pull requests merged in 2021-09, with the labels that each got.

#960 DEVHUB-798: Remove hyphens auto
  src/components/Literal.js
  src/templates/article.js
  tests/unit/__snapshots__/DefinitionList.test.js.snap
Labels: front-end

#965 Deploy DEVHUB-798: Remove hyphens auto (#960)
  src/components/Literal.js
  src/templates/article.js
  tests/unit/__snapshots__/DefinitionList.test.js.snap
Labels: Release

#959 DEVHUB-583: Fix Directive Warnings (Break, Delete, Golang)
  src/components/Break.js
  src/components/ComponentFactory.js
  src/components/Delete.js
  src/utils/determine-correct-leafygreen-language.js
Labels: enhancement, front-end

#966 Deploy DEVHUB-583, Plus Symbol in DecodeURI
  src/components/Break.js
  src/components/ComponentFactory.js
  src/components/Delete.js
  src/utils/determine-correct-leafygreen-language.js
  src/utils/query-string.js
Labels: Release

#958 DEVHUB-810: Add Cypress Testing for Community Champions
  cypress/integration/community-champions/entry.js
  cypress/integration/community-champions/profile.js
  src/components/pages/community-champions/meet-the-champions.js
  src/components/pages/community-champions/profile/certifications-and-awards.js
  src/components/pages/community-champions/profile/links-section.js
Labels: enhancement

#907 DEVHUB-780: Swap Nav to Consistent Nav
  .eslintrc.js
  .github/workflows/devhub-ci-test.yaml
  .github/workflows/devhub-npm-test.yaml
  .npmrc
  README.md
  cypress/integration/nav.js
  cypress/integration/search.js
  cypress/support/commands.js
  lighthouserc.json
  package-lock.json
  package.json
  src/components/dev-hub/article-schema.js
  src/components/dev-hub/consistent-nav.js
  src/components/dev-hub/global-footer.js
  src/components/dev-hub/global-nav.js
  src/components/dev-hub/layout.js
  tests/unit/ArticleSchema.test.js
Labels: front-end

#979 Release New Nav
  .eslintrc.js
  .github/workflows/devhub-ci-test.yaml
  .github/workflows/devhub-npm-test.yaml
  .npmrc
  Makefile
  README.md
  cypress/integration/community-champions/entry.js
  cypress/integration/community-champions/profile.js
  cypress/integration/nav.js
  cypress/integration/search.js
  cypress/support/commands.js
  gatsby-config.prod-new.js
  lighthouserc.json
  package-lock.json
  package.json
  src/components/dev-hub/article-schema.js
  src/components/dev-hub/consistent-nav.js
  src/components/dev-hub/global-footer.js
  src/components/dev-hub/global-nav.js
  src/components/dev-hub/layout.js
  src/components/pages/community-champions/meet-the-champions.js
  src/components/pages/community-champions/profile/certifications-and-awards.js
  src/components/pages/community-champions/profile/links-section.js
  tests/unit/ArticleSchema.test.js
Labels: Release

#981 DEVHUB-848: Use grid sizing to prevent jumpy anchor link
  src/components/dev-hub/consistent-nav.js
  src/pages/learn.js
Labels: bug

#982 DEVHUB-850: Fix Dep Error on Champions Modal
  cypress/integration/community-champions/entry.js
  package-lock.json
  package.json
Labels: bug

#980 DEVHUB-849: Accept lowercase content filters
  src/pages/learn.js
Labels: bug

#983 Release: September 21, 2021
  cypress/integration/community-champions/entry.js
  package-lock.json
  package.json
  src/components/dev-hub/consistent-nav.js
  src/pages/learn.js
Labels: Release

#964 Devhub 819
  .dockerignore
  .drone.yml
  Dockerfile
  environments/prod.yaml
  environments/staging.yaml
  gatsby-node.esm.js
  src/utils/setup/handle-create-home-page.js
Labels: build-time logic, release-window

#978 Devhub 820 academia form changes
  package-lock.json
  package.json
  src/components/dev-hub/academia-sign-up-form.js
  src/components/dev-hub/select.js
  src/components/pages/educators/sign-up-modal.js
Labels: enhancement

#990 Deploy DEVHUB-819, Nav v 21
  .drone.yml
  .npmrc
  Dockerfile
  package-lock.json
  package.json
Labels: Release

#991 DEVHUB-857: Update copy for Academia Student benefits
  src/components/pages/academia/students-educators-details.js
Labels: front-end, release-window
